name: ci
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
# Spend CI time only on latest ref
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  check:
    uses: ./.github/workflows/check.yml
  test:
    uses: ./.github/workflows/test.yml
  nostd:
    uses: ./.github/workflows/nostd.yml
  safety:
    uses: ./.github/workflows/safety.yml
